{{/*
Copyright (c) HashiCorp, Inc.
SPDX-License-Identifier: MPL-2.0
*/}}

{{- if .Values.agents.namespace.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}-agents
  {{- with .Values.agents.namespace.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agents.namespace.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
