# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

{{ if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: terraform-enterprise
  namespace: {{ .Release.Namespace }}
  {{- with .Values.pdb.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.pdb.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  minAvailable: {{ .Values.pdb.replicaCount }}
  selector:
    matchLabels:
      app: terraform-enterprise
{{ end }}
