# Copyright IBM Corp. 2023, 2025
# SPDX-License-Identifier: MPL-2.0

{{- if and (not .Values.preupgradeCheck.enabled) .Values.csi.enabled }}
{{- $provider := .Values.csi.provider | default "vault" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.secretProviderClass }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.csi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.csi.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider: {{ $provider }}
  {{- if .Values.csi.parameters }}
  parameters:
    {{- toYaml .Values.csi.parameters | nindent 4 }}
  {{- else if eq $provider "vault" }}
  parameters:
    roleName: "{{ .Values.csi.vaultRole }}"
    vaultAddress: "{{ .Values.csi.vaultAddress }}"
    objects: |
    {{- range .Values.csi.secrets }}
      - objectName: "{{ .objectName }}"
        secretPath: "{{ .secretPath }}"
        secretKey: "{{ .secretKey }}"
    {{- end }}
  {{- end }}
  {{- if .Values.csi.secretObjects }}
  secretObjects:
    {{- toYaml .Values.csi.secretObjects | nindent 4 }}
  {{- end }}
{{- end }}
