{{/*
Copyright (c) HashiCorp, Inc.
SPDX-License-Identifier: MPL-2.0
*/}}

{{- if and .Values.tls.certData .Values.tls.keyData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.certificateSecret }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certData }}
  tls.key: {{ .Values.tls.keyData }}
{{- end }}

{{- if and .Values.tlsSecondary.certData .Values.tlsSecondary.keyData }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tlsSecondary.certificateSecret | default "terraform-enterprise-certificates-secondary" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsSecondary.certData }}
  tls.key: {{ .Values.tlsSecondary.keyData }}
{{- end }}


{{- if .Values.tls.caCertData }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: terraform-enterprise-ca-certificates
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.tls.caCertFileName }}: {{ .Values.tls.caCertData }}
{{- end }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: terraform-enterprise-env-secrets
  namespace: {{ .Release.Namespace }}
data:
{{- include "helpers.list-env-secrets" . | indent 2 }}
