# Copyright IBM Corp. 2023, 2025
# SPDX-License-Identifier: MPL-2.0

{{- if .Values.csi.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.secretProviderClass }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.csi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.csi.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider: vault
  parameters:
    roleName: "{{ .Values.csi.vaultRole }}"
    vaultAddress: "{{ .Values.csi.vaultAddress }}"
    objects: |
    {{- range .Values.csi.secrets }}
      - objectName: "{{ .objectName }}"
        secretPath: "{{ .secretPath }}"
        secretKey: "{{ .secretKey }}"
    {{- end }}
  {{- if .Values.csi.secretObjects }}
  secretObjects:
  {{- range .Values.csi.secretObjects }}
  - data:
    {{- range .data }}
    - key: {{ .key }}
      objectName: {{ .objectName }}
    {{- end }}
    secretName: {{ .secretName }}
    type: {{ .type }}
  {{- end }}
  {{- end }}
{{- end }}
