{{/*
Copyright IBM Corp. 2023, 2025
SPDX-License-Identifier: MPL-2.0
*/}}

{{- include "helpers.preupgrade-validate-config" . }}
{{- if and .Values.serviceAccount.enabled (or (not .Values.preupgradeCheck.enabled) (eq (include "helpers.preupgrade-render-prereqs" .) "true")) }}
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  {{- if .Values.serviceAccount.name}}
  name: {{ .Values.serviceAccount.name }}
  {{- else }}
  name: {{ .Release.Namespace }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
