name: Helm Chart CI

on:
  push:

permissions:
  contents: read

jobs:
  helm_chart_ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      # Step 2: Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5

      # Step 3: Lint the Helm chart
      - name: Lint Helm chart
        run: |
          helm lint .

      # Step 4: Install kubeconform
      - name: Install kubeconform
        run: |
          curl -LO https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform-linux-amd64.tar.gz

      # Step 5: Render and validate Helm templates
      - name: Validate rendered Helm templates
        run: |
          helm template . | ./kubeconform --strict
